// Copyright (c) 2017 Matthew Brennan Jones <matthew.brennan.jones@gmail.com>
// This software is licensed under a MIT License
// https://github.com/workhorsy/uncompress.js
"use strict";
function loadScript(f,k){if("object"===typeof window){var l=document.createElement("script");l.type="text/javascript";l.src=f;l.onload=function(){k&&k()};document.head.appendChild(l)}else"function"===typeof importScripts&&(importScripts(f),k&&k())}function currentScriptPath(){try{throw Error("");}catch(k){var f=k.stack;f=-1!==f.indexOf("@")?f.split("@")[1].split("\n")[0]:f.split("(")[1].split(")")[0];return f=f.substring(0,f.lastIndexOf("/"))+"/"}}var unrarMemoryFileLocation=null,g_on_loaded_cb=null;
(function(){function f(a,d){for(var b="",c=0;c<a.length;++c)b=0===c?b+a[c]:b+(d+a[c]);return b}function k(a,d){for(var b=Array(a.length),c=0;c<b.length;++c)b[c]=d(a[c]);return b}function l(a,d,b){var c=null;if(n(b))c="rar";else if(p(b))c="zip";else if(q(b))c="tar";else throw Error("The archive type is unknown");if(-1===m.indexOf(c))throw Error("The archive format '"+c+"' is not loaded.");var e=null,g=[];try{switch(c){case "rar":e=r(a,d,b);g=t(e);break;case "zip":e=u(a,d,b);g=v(e);break;case "tar":e=
{file_name:a,array_buffer:b,password:d},g=w(e)}}catch(z){throw Error("Failed to open '"+c+"' archive.");}g.sort(function(a,b){return a.name<b.name?-1:a.name>b.name?1:0});return{file_name:a,archive_type:c,array_buffer:b,entries:g,handle:e}}function r(a,d,b){var c=[{name:a,size:b.byteLength,type:"",content:new Uint8Array(b)}];return{file_name:a,array_buffer:b,password:d,rar_files:c}}function u(a,d,b){var c=new JSZip(b);return{file_name:a,array_buffer:b,password:d,zip:c}}function t(a){var d=readRARFileNames(a.rar_files,
a.password),b=[];Object.keys(d).forEach(function(c){var e=d[c].name,g=d[c].is_file;b.push({name:e,is_file:d[c].is_file,size_compressed:d[c].size_compressed,size_uncompressed:d[c].size_uncompressed,readData:function(b){setTimeout(function(){if(g)try{readRARContent(a.rar_files,a.password,e,b)}catch(x){b(null,x)}else b(null,null)},0)}})});return b}function v(a){var d=a.zip,b=[];Object.keys(d.files).forEach(function(a){var c=d.files[a],g=!c.dir;b.push({name:c.name,is_file:g,size_compressed:c._data?c._data.compressedSize:
0,size_uncompressed:c._data?c._data.uncompressedSize:0,readData:function(a){setTimeout(function(){if(g){var b=c.asArrayBuffer();a(b,null)}else a(null,null)},0)}})});return b}function w(a){var d=[];tarGetEntries(a.file_name,a.array_buffer).forEach(function(b){var c=b.is_file,e=b.size;d.push({name:b.name,is_file:c,size_compressed:e,size_uncompressed:e,readData:function(d){setTimeout(function(){if(c){var e=tarGetEntryData(b,a.array_buffer);d(e.buffer,null)}else d(null,null)},0)}})});return d}function n(a){var d=
f([82,69,126,94],", "),b=f([82,97,114,33,26,7,0],", "),c=f([82,97,114,33,26,7,1,0],", ");if(8>a.byteLength)return!1;var e=f((new Uint8Array(a)).slice(0,4),", "),g=f((new Uint8Array(a)).slice(0,7),", ");a=f((new Uint8Array(a)).slice(0,8),", ");return e===d||g===b||a===c}function p(a){var d=f([80,75,3,4],", ");return 4>a.byteLength?!1:f((new Uint8Array(a)).slice(0,4),", ")===d}function q(a){var d=f(["u","s","t","a","r"],", ");return 512>a.byteLength?!1:f(k((new Uint8Array(a)).slice(257,262),String.fromCharCode),
", ")===d}var m=[];"undefined"===typeof Uint8Array||Uint8Array.prototype.slice||(Uint8Array.prototype.slice=function(a,d){for(var b=new Uint8Array(d-a),c=0,e=a;e<d;++e)b[c]=this[e],c++;return b});var h=null;"object"===typeof window?h=window:"function"===typeof importScripts&&(h=self);h.loadArchiveFormats=function(a,d){var b=currentScriptPath(),c=0,e=function(){c++;var b=a.length;-1!==a.indexOf("rar")&&"object"===typeof window&&b++;c===b&&d()};g_on_loaded_cb=e;a.forEach(function(a){if(-1===m.indexOf(a))switch(a){case "rar":unrarMemoryFileLocation=
b+"libunrar.js.mem";loadScript(b+"libunrar.js",e);m.push(a);break;case "zip":loadScript(b+"jszip.js",e);m.push(a);break;case "tar":loadScript(b+"libuntar.js",e);m.push(a);break;default:throw Error("Unknown archive format '"+a+"'.");}})};h.archiveOpenFile=function(a,d,b){var c=a.slice(),e=a.name;d=d||null;var f=new FileReader;f.onload=function(a){a=f.result;try{var c=l(e,d,a);b(c,null)}catch(y){b(null,y)}};f.readAsArrayBuffer(c)};h.archiveOpenArrayBuffer=l;h.archiveClose=function(a){a.file_name=null;
a.archive_type=null;a.array_buffer=null;a.entries=null;a.handle=null};h.isRarFile=n;h.isZipFile=p;h.isTarFile=q;h.saneJoin=f;h.saneMap=k})();
